### ISSUE TITLE
Remove from conda-forge

### ISSUE THREAD

**Issue by wigging** [wigging/chemics#26]
@jan-janssen Please remove chemics from the conda-forge repository. I'm in the process of moving chemics to my personal GitHub account where I will continue its development. Future versions will rely on pip for the installation process.

**Comment by jan-janssen** [comment]
The conda-forge version also uses the pip version.

**Comment by wigging** [comment]
Yes, but how do I delete the conda-forge version. I think you need to delete the feedstock at https://github.com/conda-forge/chemics-feedstock.

**Comment by wigging** [comment]
I transferred the repo from the GitHub organization to my personal account. Not sure if the transfer affected the conda-forge version but going forward I will recommend installing chemics only with pip.
