### ISSUE TITLE
Move fluidization code, docs, examples, and tests

### ISSUE THREAD

**Issue by wigging** [wigging/chemics#27]
Move fluidization code, tests, and documentation to the tavy package. See below for a checklist of items that need to be moved from chemics to tavy.

Code
- [x] bed_expansion_factor.py
- [x] bubble_diameter.py
- [x] bubble_fraction.py
- [x] bubble_rise_velocity.py
- [x] choking_velocity.py
- [x] devol_time.py
- [x] emulsion.py
- [x] geldart.py
- [x] mass_transfer_correlations.py
- [x] minimum_fluidization_velocity.py
- [x] pressure_drop.py
- [x] residence_time.py
- [x] terminal_velocity.py
- [x] transport_disengaging_height.py
- [x] transport_velocity.py

Documentation
- [x] bed_expansion_factor.rst
- [x] bubble_rise_velocity.rst
- [x] choking_velocity.rst
- [x] devol_time.rst
- [x] geldart.rst
- [x] mass_transfer_correlations.rst
- [x] minimum_fluidization_velocity.rst
- [x] pressure_drop.rst
- [x] terminal_velocity.rst
- [x] transport_disengaging_height.rst
- [x] transport_velocity.rst

Examples
- [x] bed_expansion_factor.py
- [x] bubble_velocity.py
- [x] devol_time.py
- [x] geldart.py
- [x] minimum_fluidization_velocity.py
- [x] rtd_cstr_vusse.ipynb
- [x] rtd_weibull.ipynb
- [x] terminal_velocity.py
- [x] transport_disengaging_height.py
- [x] transport_velocity.py
- [x] uch_compare.py

Tests
- [x] test_bed_expansion_factor.py
- [x] test_bubble_rise_velocity_holland.py
- [x] test_bubble_rise_velocity_kunii.py
- [x] test_devol_time.py
- [x] test_mass_transfer_correlations.py
- [x] test_minimum_fluidization_velocity.py
- [x] test_pressure_drop.py
- [x] test_terminal_velocity.py
- [x] test_transport_disengaging_height.py
- [x] test_transport_velocity.py

**Comment by wigging** [comment]
All code, tests, examples, and documentation related to fluidization have been moved to the tavy package. I'll share a link (in this issue) to the package once it's on GitHub.

**Comment by wigging** [comment]
The tavy package will be available at https://github.com/wigging/tavy

**Comment by NoobixCube** [comment]
Is anyone else having trouble with the tavy link?

**Comment by NoobixCube** [comment]
> The tavy package will be available at https://github.com/wigging/tavy

Getting a 404 error.

**Comment by wigging** [comment]
@NoobixCube The link doesn't work because the repository is private. Once it's public then the link will work.

**Comment by NoobixCube** [comment]
> @NoobixCube The link doesn't work because the repository is private. Once it's public then the link will work.

Got it.
Thanks!
