### ISSUE TITLE
ValueError: Gas viscosity for NH3 is not available.

### ISSUE THREAD

**Issue by defencedog** [wigging/chemics#28]
[chemic_gasrho.zip](https://github.com/wigging/chemics/files/10300743/chemic_gasrho.zip)
Need to update database I suppose

```
File /data/data/com.termux/files/usr/lib/python3.9/site-packages/chemics/gas_viscosity.py:147, in mu_gas(formula, temp, cas, full)
    144     return mu
    146 else:
--> 147     raise ValueError(f'Gas viscosity for {formula} is not available.')
ValueError: Gas viscosity for NH3 is not available.
```

**Comment by wigging** [comment]
Use H3N instead of NH3 for ammonia.

```python
import chemics as cm
mu = cm.mu_gas('H3N', 900)
print('mu is', mu)
```

This prints the following:

```
mu is 319.14247215113517
```

**Comment by defencedog** [comment]
Thanks, So Chemical names are alphabetically arranged? Should I write `ClH` instead of `HCl` ?

**Comment by wigging** [comment]
Yes, it looks like most of the chemical formulas in the Yaw's data are alphabetically listed. So for HCl you should use `cm.mu_gas('ClH', 900)`. You can look up formulas in [PubChem](https://pubchem.ncbi.nlm.nih.gov/compound/313) to see their alternate spelling. Another approach is to use the CAS number, but chemics only uses this if there are similar formulas in the database. I should fix it such that if the CAS number is given, then it overrides the formula. That way you could just provide the CAS number without the formula.

**Comment by defencedog** [comment]
The gas viscosity is also pressure dependant but the function only takes temperature as input. Please elaborate.

**Comment by wigging** [comment]
The `mu_gas()` function is only temperature dependent because it is calculated from coefficients in Yaws’ Critical Property Data for Chemical Engineers and Chemists. See the Chemics [documentation](https://chemics.readthedocs.io/en/latest/gas_viscosity.html) for more information about the function.
